### PR TITLE
Add usage example of /InsertDesktop to README.md

### PR DESCRIPTION
**Pull request by LinqLover**
See #19. Actually, it took me way too long to figure out how two arbitrary desktops can be inserted/swapped, so perhaps this might be worth an entry in the README.md. 😅

### CODE REVIEW

**Comment by MScholtes** [comment]
Thank you very much for your note

**Comment by LinqLover** [comment]
Did you remove the example by accident again?

https://github.com/MScholtes/VirtualDesktop/commit/64291799963deaa8709dec11bef750e62a4594f1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L120-L122

**Comment by MScholtes** [comment]
No, starting with Windows 11 there is an API function "MoveDesktop" that does a similiar job and replaces InsertDesktop. To avoid misunderstandings I removed the example that only works with the Windows 10 version of the tool.

Greetings

Markus

**Comment by LinqLover** [comment]
Ah, I see, thanks. I'm still on Windows 10 (and will probably stay there for some time). Maybe add a git tag for each older version? :-)

**Pull request merged**
