### PR TITLE
/WaitDesktopChange /WDC

### PR DESCRIPTION
**Pull request by jonathan-annett**
waits until the current desktop has changed before next continuing

(also changes the compile.bat strategy to build/test each version until a working candidate is found, always produces output as VirtualDeskop.exe regardless of what version is used)

### CODE REVIEW

**Comment by jonathan-annett** [comment]
I decided to leave the compile.bat as is, and created a build.bat instead which implements the "build for this pc" logic

i've also added a package.json file the repo can be included as a sub package - i'm creating a nodejs/electrol/nwjs module that implements desktop switching on windows.

commit [6e6f2c806fed397cc474e90aa99ca4854a14aece](https://github.com/MScholtes/VirtualDesktop/pull/74/commits/6e6f2c806fed397cc474e90aa99ca4854a14aece) has all these changes)

**Comment by jonathan-annett** [comment]
added an interactive mode (will mainly be used by node.js wrapper, to stay running, report changes, and respond to commands via stdin (uses same format as command line, with a few commands omitted)

**Comment by MScholtes** [comment]
Hello @jonathan-annett,

I will not merge your pull request because
- I do not see any use in a Javascript integration of VirtualDesktop
- see my contribution guide

Greetings

Markus

**Comment by jonathan-annett** [comment]
All good. I'll keep your credit in my repo and link back to it

(There is a use BTW. Google bitfocus companion)

**Comment by jonathan-annett** [comment]
Fyi

https://github.com/bitfocus/companion/wiki/Module-Development

https://github.com/jonathan-annett/virtual-desktop-node

https://github.com/jonathan-annett/companion-module-sophtwhere-virtual-desktop

**Pull request closed without merging**
